[package]
name = "theframework"
version = "0.1.1"
edition = "2021"
description = "A cross platform application UI framework."
license = "MIT"
keywords = ["application", "framework", "graphics", "user-interface", "ui", "gui", "cross-platform"]
repository = "https://github.com/markusmoenig/theframework.git"
exclude = ["images"]

[dependencies]
env_logger = "0.10"
log = "0.4"
fontdue = "0.8.0"
maths-rs = { version = "0.2", features = ["short_types", "short_hand_constructors", "casts", "serde"] }
pixels = { version = "0.13.0", optional = true }
winit = { version = "0.28.7", optional = true }
winit_input_helper = { version = "0.14.1", optional = true }
therenderer = { version = "0.1.0", optional = true }
#therenderer = { path = "../therenderer" }
rust-embed = { version = "8.0.0", default-features = true, features = ["include-exclude"] }
png = "0.17.8"
rustc-hash = "1.1.0"
rfd = { version = "0.12", optional = true }
futures = { version = "0.3", optional = true }
serde = { version = "1.0", features = ["derive"], optional = false}
serde_json = { version = "1.0", optional = false }
flate2 = { version = "1.0", optional = true }
vectorize = "0.2.0"

[dependencies.uuid]
version = "1.1.2"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
    "serde"
]

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1"
console_log = "1.0.0"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["GpuTextureFormat"] }

[features]
renderer = ["therenderer"]
ui = ["futures", "rfd", "flate2"]
code = []
pixels_winit = ["pixels", "winit", "winit_input_helper"]
default = ["pixels_winit"]

[workspace]
members = [
    "examples/*",
    "run-wasm",
]
