[package]
name = "circle"
version = "0.1.0"
edition = "2021"

[dependencies]
theframework = { path = "../..", default-features = false, features = [
    "winit_app",
] }
lazy_static = "1.4.0"

[lib]
name = "rustapi"
crate-type = ["staticlib"]
