[package]
name = "codedemo"
version = "0.1.0"
edition = "2021"

[dependencies]
theframework = { path = "../..", features = ["ui", "code"] }
lazy_static = "1.4.0"

# [lib]
# name = "rustapi"
# crate-type = ["staticlib"]